apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spalabfinal-restapi
  labels:
    app: spalabfinal
    tier: restapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: spalabfinal
        tier: restapi
    spec:
      containers:
      - name: spalabfinal-app
        image: gcr.io/augmented-world-201715/spa-lab-final@sha256:162823d5b1742b10f2e055b31ce931d77d7f77e38a9f8c7b11b8baacbece98c6
        command: ["spa-lab-final"]
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8000
